"""Contratos soberanos V6 — CFO-02: contrato antes de implementação."""

from contracts.indicator_contract import (
    IndicatorEngine,
    IndicatorError,
    IndicatorInput,
    IndicatorOutput,
)
from contracts.market_data_contract import (
    BarRequest,
    ConnectionError,
    DataIntegrityError,
    DataProvider,
    FeedSpec,
    FetchResult,
    MarketDataEngine,
    MarketDataError,
    MarketDataFeed,
    MarketDataSnapshot,
    OHLCVBar,
    ProviderConfig,
    UnsupportedSymbolError,
    UnsupportedTimeframeError,
)
from contracts.position_contract import (
    ExposureSummary,
    PositionDesyncError,
    PositionError,
    PositionEvent,
    PositionManager,
    PositionNotFoundError,
    PositionSide,
    PositionSnapshot,
    PositionStateError,
    PositionStatus,
    PositionSyncAdapter,
    PositionSyncError,
    PositionTicket,
)

__all__ = [
    "IndicatorEngine",
    "IndicatorError",
    "IndicatorInput",
    "IndicatorOutput",
    "BarRequest",
    "ConnectionError",
    "DataIntegrityError",
    "DataProvider",
    "FeedSpec",
    "FetchResult",
    "MarketDataEngine",
    "MarketDataError",
    "MarketDataFeed",
    "MarketDataSnapshot",
    "OHLCVBar",
    "ProviderConfig",
    "UnsupportedSymbolError",
    "UnsupportedTimeframeError",
    "ExposureSummary",
    "PositionDesyncError",
    "PositionError",
    "PositionEvent",
    "PositionManager",
    "PositionNotFoundError",
    "PositionSide",
    "PositionSnapshot",
    "PositionStateError",
    "PositionStatus",
    "PositionSyncAdapter",
    "PositionSyncError",
    "PositionTicket",
]
